# Generated by Django 3.1 on 2020-08-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='imageUrl',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
